[package]
name = "Mia"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"

# Web & Socket
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7", features = ["ws"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tower-http = { version = "0.5", features = ["fs"] }

# Discord & Audio
serenity = { version = "0.12", features = ["builder", "gateway", "http", "model", "client", "voice"] }
songbird = { version = "0.4" }

# Symphonia avec le support complet (MP3, FLAC, WAV, et MP4/AAC)
symphonia = { version = "0.5", features = ["aac", "isomp4", "mp3", "flac", "vorbis", "wav"] }